### PR TITLE
Add support for collections to ansible-local provisioner

### LINKED ISSUE #32: Ansible Collections get ignored by default using ansible-local provisioner
_This issue was originally opened by @emansom as hashicorp/packer#10666. It was migrated here as a result of the [Packer plugin split](https://github.com/hashicorp/packer/issues/8610#issuecomment-770034737). The original body of the issue is below._

<hr>

#### Overview of the Issue

Providing the `ansible-local` provisioner with a [`galaxy_file`](https://github.com/hashicorp/packer/blob/v1.7.0/provisioner/ansible-local/provisioner.go#L68) results in no Ansible Collections being installed.

Upstream Ansible project are [aware](https://github.com/ansible/ansible/pull/67843) of this issue and have [documented](https://github.com/ansible/ansible/pull/67843#issuecomment-629572885) when the behavior of the `ansible-galaxy` results in installation of collections and roles and when not. Following table created by @jborean93 eleborates on it further:
| Command                                                 | Installed roles?     | Installed collections?  | Change in behaviour                           |
|---------------------------------------------------------|----------------------|-------------------------|-----------------------------------------------|
| `ansible-galaxy install -r requirements.yml`            | Yes                  | Yes                     | Will install collections as well as roles     |
| `ansible-galaxy role install -r requirements.yml`       | Yes                  | No (warning in -vvv)    | Adds msg in -vvv that collections are skipped |
| `ansible-galaxy collection install -r requirements.yml` | No (warning in -vvv) | Yes                     | Adds msg in -vvv that roles are skipped       |
| `ansible-galaxy install -r requirements.yml -p ./`      | Yes                  | No (warning in default) | Adds warning saying collections are skipped   |

#### Potential fix

Removing the `-p` argument from the `ansible-galaxy` command invocation results in the desired behavior of both roles and collections being installed. I locally use a forked version of Packer with [this patch](https://github.com/emansom/packer/commit/242b327e73f41886a67dd918174279476b2936ef) applied with success.

There's a [PR](https://github.com/hashicorp/packer/pull/10667) containing this patch to be applied, before or after further rework.

#### Reproduction Steps

Attempt to install a Ansible Collection using the `ansible-local` provisioner, see provided files below to reproduce. Modify builder type to your needs accordingly; the builder type is not a prerequisite.

### Packer version

`Packer version: 1.6.5 [go1.15.5 linux amd64]`

### Packer Buildfile

`centos8-nginx-lxd.json`
```
{
  "provisioners": [
    {
      "type": "shell",
      "inline": "dnf makecache && dnf -y install epel-release && dnf makecache && dnf install -y python39 libsodium python3-bcrypt python3-paramiko python3-pynacl sshpass python3-pyyaml python3-jinja2 platform-python-pip python3-pip && alternatives --set python /usr/bin/python3.9 && pip3 install ansible"
    },
    {
      "type": "ansible-local",
      "galaxy_file": "requirements.yml",
      "playbook_file": "playbook.yml",
      "extra_arguments": [
        "ansible_python_interpreter=/usr/bin/python3.9"
      ]
    }
  ],
  "builders": [
    {
      "type": "lxd",
      "name": "centos-nginx",
      "image": "images:centos/8-Stream",
      "output_image": "centos-8-nginx-test"
    }
  ]
}
```

### Ansible Playbook

`playbook.yml`
```
---
- hosts: 127.0.0.1
  connection: local
  collections:
    - nginxinc.nginx_core
  roles:
    - role: nginx
```

### Ansible Collections requirements file
`requirements.yml`
```
---
collections:
  - name: nginxinc.nginx_core
    version: 0.3.0
```

### Operating system and Environment details

Workstation running Linux, latest stable Packer and LXD.

### Log Fragments and crash.log files

See following [gist](https://gist.github.com/emansom/61cd34555b96dda6230e32d962d66e1a). Excerpt where it goes haywire:
```
2021/02/19 21:19:39 packer-builder-lxd plugin: Executing lxc exec: /bin/sh []string{"/bin/sh", "-c", "lxc exec packer-acme-focal -- /bin/sh -c \"cd /tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2 && ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2/playbook.yml --extra-vars \"packer_build_name=acme-focal packer_builder_type=lxd packer_http_addr=ERR_HTTP_ADDR_NOT_IMPLEMENTED_BY_BUILDER -o IdentitiesOnly=yes\" -vv ansible_python_interpreter=/usr/bin/python3.9 -c local -i /tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2/packer-provisioner-ansible-local240743931\""}
==> acme-focal: [WARNING]: No inventory was parsed, only implicit localhost is available
==> acme-focal: [WARNING]: provided hosts list is empty, only localhost is available. Note that
==> acme-focal: the implicit localhost does not match 'all'
==> acme-focal: ERROR! the role 'nginx' was not found in nginxinc.nginx_core:ansible.legacy:/tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2
==> acme-focal: 
==> acme-focal: The error appears to be in '/tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2/playbook.yml': line 7, column 7, but may
==> acme-focal: be elsewhere in the file depending on the exact syntax problem.
==> acme-focal: 
==> acme-focal: The offending line appears to be:
==> acme-focal: 
==> acme-focal:   roles:
==> acme-focal:     - role: nginx
==> acme-focal:       ^ here
2021/02/19 21:19:39 packer-builder-lxd plugin: lxc exec execution exited with '1': 'cd /tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2 && ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2/playbook.yml --extra-vars "packer_build_name=acme-focal packer_builder_type=lxd packer_http_addr=ERR_HTTP_ADDR_NOT_IMPLEMENTED_BY_BUILDER -o IdentitiesOnly=yes" -vv ansible_python_interpreter=/usr/bin/python3.9 -c local -i /tmp/packer-provisioner-ansible-local/60301cdb-5fcb-3f4b-cc3f-515856a077d2/packer-provisioner-ansible-local240743931'
```

### PR DESCRIPTION
**Pull request by nywilken**
Closes #32, https://github.com/hashicorp/packer/issues/10666
Alternative to https://github.com/hashicorp/packer/pull/10667

This pull-request was migrated over from https://github.com/hashicorp/packer/pull/10768

### CODE REVIEW

**Comment by wilsonge** [comment]
happy to continue helping with this (sorry I moved house so let it go unattended for a while). but unsure after this split how to test this locally. there's been no nightly of packer on github since the ansible code was split out :(

**Comment by SwampDragons** [comment]
You can test it with the current Packer nightly; to build and test the Ansible plugin from source, you can clone this repo, change directories into the repo dir, and call `go build -o packer-plugin-ansible`. This will create a binary in your current working directory called packer-plugin-ansible. You can move this binary into the working directory for your test template, and when you call `packer build yourtesttemplate.pkr.hcl` it will automatically discover the ansible plugin binary and use it instead of the one vendored into the packer core.

**Comment by mmerfort** [comment]
This would be really useful to have.

**Comment by leeovery** [comment]
Whilst we wait for this to be merged, what is a good workaround please. Ive tried a few things Ive researched but nothing seems to do the job. Newbie to Ansible + packer - so Im sure its an obvious fix but its evading me at the mo - and Im probs not alone.

Thanks!

**Review by lbajolet-hashicorp — APPROVED** [review]
LGTM, there's a conflict with the documentations that needs to be fixed before merging, but outside of that I don't have anything to add

**Comment by emansom** [comment]
> Whilst we wait for this to be merged, what is a good workaround please. Ive tried a few things Ive researched but nothing seems to do the job. Newbie to Ansible + packer - so Im sure its an obvious fix but its evading me at the mo - and Im probs not alone.
> 
> Thanks!

There's a [handy matrix](https://github.com/ansible/ansible/pull/67843#issuecomment-629572885) eleborating on Ansible's default behavior handling Galaxy files.

The quickest workaround would be invoking the [shell provisioner ](https://www.packer.io/docs/provisioners/shell) to install Ansible and invoke it with `ansible-galaxy install -r requirements.yml`.

**Comment by emansom** [comment]
@nywilken Thanks for figuring this out and implementing a solution! 🙌🏻 🎉

**Pull request merged**
