### PR TITLE
Fix missing space between ssh extra args

### LINKED ISSUE #116: Options in ansible_ssh_extra_args  not properly concatenated
## Issue description

When specifying multiple value options in `ansible_ssh_extra_args` they are concatenated without spacing, breaking the SSH command.

Example:

```
  provisioner "ansible" {
    playbook_file           = "./ansible/playbook.yml"

    use_proxy               =  false
    ansible_ssh_extra_args  = [
      "-o StrictHostKeyChecking=no",
      "-o PubkeyAuthentication=yes",
    ]
  }
```

### Current behaviour

The options are collapsed into one _(note the lack of space after `StrictHostKeyChecking=no`)_:

```
Executing Ansible: ansible-playbook [..] --ssh-extra-args '-o StrictHostKeyChecking=no-o PubkeyAuthentication=yes' /path/to/ansible/playbook.yml
```

### Expected behaviour

``
Executing Ansible: ansible-playbook [..] --ssh-extra-args '-o StrictHostKeyChecking=no -o PubkeyAuthentication=yes' /path/to/ansible/playbook.yml
```


### Additional information

_Workaround_: Currently the only woraround I founf is to add a leading/trailing space to the 


OS: Linux
Packer ver: 1.8.3
Ansible ver: 2.12.2

Source:
https://github.com/hashicorp/packer-plugin-ansible/blob/82d329f7da94ce282663416eade6c9a3edfa4355/provisioner/ansible/provisioner.go#L776-L783

### PR DESCRIPTION
**Pull request by rodolpheche**
Hi,

When passing more than one ssh extra arg, they are concatenated without a space between them.

Using strings.Join fixes the issue.

Closes #116

### CODE REVIEW

**Review by nywilken — APPROVED** [review]
LGTM

**Comment by nywilken** [comment]
The change looks good to me. But I need to see why the test are failing here.

**Comment by rodolpheche** [comment]
The tests failed because of missing quotes around ssh extra args, it's now fixed

**Review by nywilken — APPROVED** [review]
LGTM - thanks for updating the tests

**Pull request merged**
